[project]
name = "hinty"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

# [build-system]
# requires = ["uv_build>=0.9.0,<0.10.0"]
# build-backend = "uv_build"

[dependency-groups]
dev = []

[project.scripts]
# hinty = "hinty.main:cli"
