[project]
name = "hinty"
version = "0.1.0"
description = "My agent to get long-term in code"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "baml-py>=0.209.0",
    "dotenv>=0.9.9",
    "loguru>=0.7.3",
    "pydantic>=2.11.9",
    "rich>=14.1.0",
    "typer>=0.19.2",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
  "catppuccin-jupyterlab>=0.2.4",
  "jupyterlab>=4.4.9",
  "jupyterlab-vim>=4.1.4",
]

[project.scripts]
hinty = "hinty.main:cli"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"river" = ["**/*.txt", "**/*.json"]
